package com.cubic.entity;

public interface QueryConstants {
	
	String PRODUCT_SEARCH_BY_NAME = "PRODUCT_SEARCH_BY_NAME";
	
	String PRODUCT_SEARCH_BY_NUMBER = "PRODUCT_SEARCH_BY_NUMBER";
	
	String PRODUCT_SEARCH_BY_UPC = "PRODUCT_SEARCH_BY_UPC";
	
	String PRODUCT_SEARCH_BY_MANUFACTURE= "PRODUCT_SEARCH_BY_MANUFACTURE";
	
	String PRODUCT_SEARCH_BY_CATAGORY= "PRODUCT_SEARCH_BY_CATAGORY";


}
